### ISSUE TITLE
[PC] Proxy error: Command too small (expected at least 0x150 bytes, received 0x14C bytes)

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#134] opened 2023-10-04 01:56 UTC
Proxied over to a non-newserv server, attempted to create game, received the below log:
```
I 20632 2023-10-04 02:49:07 - [Commands] Received from LinkedSession:3CB021DE:client (version=PC command=10 flag=00)
0000 | 0C 00 10 00 06 00 00 00 00 00 00 00             |                 
I 20632 2023-10-04 02:49:07 - [Commands] Received from LinkedSession:3CB021DE:server (version=PC command=64 flag=01)
0000 | 50 01 64 01 00 00 00 00 00 00 00 00 00 00 00 00 | P d             
0010 | 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0020 | 01 00 00 00 01 00 00 00 01 00 00 00 01 00 00 00 |                 
0030 | 01 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 |                 
0040 | 01 00 00 00 01 00 00 00 01 00 00 00 01 00 00 00 |                 
0050 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0060 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0070 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0080 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0090 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
00A0 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
00B0 | 00 00 00 00 00 00 01 00 D9 37 00 00 FF FF FF FF |          7      
00C0 | 01 00 00 00 4D 00 61 00 74 00 74 00 00 00 00 00 |     M a t t     
00D0 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
00E0 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
00F0 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0100 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0110 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0120 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0130 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0140 | 00 00 00 00 01 01 01 00 00 05 06 00 BF 19 AA 19 |                 
E 20632 2023-10-04 02:49:07 - [ProxyServer:LinkedSession:3CB021DE] Failed to process command: command too small (expected at least 0x150 bytes, received 0x14C bytes)
```
In-game returns the following:
![image](https://github.com/fuzziqersoftware/newserv/assets/33199242/0799e1b6-77aa-4954-8ac3-c72079efbf38)

**Comment by fuzziqersoftware** [comment] 2023-10-04 02:38
This is caused by some ancient laziness - newserv sends an extra 4 bytes in the game join command for v1/v2 clients because v3 expects them, but this also means the proxy expects that many bytes for all versions too. This is fixed by da487124.

**Closed as completed** 2023-10-07 10:47 UTC
