### ISSUE TITLE
[BB] Other player's names are displayed wrong

### ISSUE THREAD

**Issue by toiletman74** [fuzziqersoftware/newserv#368] opened 2024-02-01 08:17 UTC
For some reason longer names get cut off on other player's screens but not on that player's screen. Example:
![image](https://github.com/fuzziqersoftware/newserv/assets/91436591/585eac56-3931-4b72-8df0-4c511a30d7a3)
![image](https://github.com/fuzziqersoftware/newserv/assets/91436591/ed6492ed-7cea-4a9f-bce1-b041442d7cb5)

also possibly related or unrelated on all addons such as the player reader or chat log, player's names other than the current player have an E in front of their name
![image](https://github.com/fuzziqersoftware/newserv/assets/91436591/3c85a038-b975-4ad1-a833-890d3f775ef5)

**Comment by nolrinale** [comment] 2024-02-22 11:08
@toiletman74 Verify this again with the latest commit that fixes the long character names on BB and close this ticket if is working as intended.

**Comment by nolrinale** [comment] 2024-03-03 13:43
@toiletman74 I verified this one with a character with a very long Japanese name and displays correctly in both windows, can we close this ticket too? 

![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/0b27a4d2-a525-42ed-ba1e-9e609d3b574a)

**Comment by fuzziqersoftware** [comment] 2024-03-05 04:05
Yes, this has been fixed on master.

**Closed by fuzziqersoftware** 2024-03-05 04:05 UTC
