### ISSUE TITLE
GC: Player cannot pick up items while playing on proxy server

### ISSUE THREAD

**Issue by clint-david** [fuzziqersoftware/newserv#24] opened 2022-06-01 00:47 UTC
Version: #(67b35901278a46a2a52bedab77fdf83a710ebca8)

Player 2 (on proxy server) will pick up item, and nothing happens.

Player 1 (on host server) can see and hear item being picked up by player 2. Item disappears on host server.

From looking at the commands being sent, it appears the item pickup and item destroy commands are not being properly forwarded?

Proxy is setup for port 9100 (using EP 1&2 GC).

**Comment by fuzziqersoftware** [comment] 2022-06-01 04:08
Thanks for the report - this looks like a bug I accidentally created when I added item tracking recently. The issue is that when an item is picked up by a non-leader player, the leader sends a subcommand with a different player's client ID, which the server rejected. It's fixed in commit 40aa08bd.

**Closed** 2022-06-02 01:19 UTC

**Comment by sirdankz** [comment] 2023-01-25 20:41
Not to be a bug but what did you use to proxy pso? I want to set up a public server but I'm not sure I should buy a VM to host or buy a vps or something similar..
