### ISSUE TITLE
EXP not working correctly in PSO BB

### ISSUE THREAD

**Issue by rumatsuki** [fuzziqersoftware/newserv#31] opened 2022-08-03 01:18 UTC
After clearing out several areas of enemies with other players, the Total EXP count still shows 0pt for everyone. I'm not sure if this is a problem with my server configuration or just a bug in newserv.

**Comment by Gamizard** [comment] 2022-08-03 01:30
Working as of newest commit.

**Comment by Gamizard** [comment] 2022-08-03 01:44
While the ability to gain EXP now works, the amount given seems to be drastically less that what it should be. Even when being the one who killed an enemy, when tested the amount actually given was 1pt.

**Comment by fuzziqersoftware** [comment] 2022-08-03 04:37
This is a known issue, which I'm pretty sure is caused by the server's .dat files not matching what the client has. Which client type and version are you using?

The correct solution is to implement a real patch server so we can be sure the files are synced; I might get to this sometime soon.

**Comment by Gamizard** [comment] 2022-08-03 04:41
I'm using a lightly modified TethVer12513 but .dat files shouldn't have been changed.

**Comment by Gamizard** [comment] 2022-08-03 14:36
Is there a way I can convert the game data from the client we use to work with newserv?

**Comment by fuzziqersoftware** [comment] 2023-09-10 17:01
Long delay here, but I believe this is fixed now (at least, in my testing with Episode 1). The client and server need to have the same .dat files for BB to work properly; the readme now contains a section specifying which files should exist in the patch-bb directory to ensure the client and server have the same map data.

**Closed by fuzziqersoftware** 2023-09-10 17:01 UTC
