### ISSUE TITLE
[Episode 3] Episode 3 engine returned an error: basic_string::_M_replace_aux

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#471] opened 2024-04-28 10:14 UTC
**Describe the bug**
Kind of as above, here's an image of the situation:

![image](https://github.com/fuzziqersoftware/newserv/assets/33199242/1517973c-e7cd-4ccf-ab16-08a286737dc0)

**To reproduce**
1. Good question

**Game version(s) (choose one or more of the following):**
GC Ep3

**Server log output**
```
I 307498 2024-04-28 10:09:12 - [Commands] Received from C-18 (PLAYER) (version=GC_EP3 command=CA flag=00)
0000 | CA 00 18 00 B3 05 00 00 28 00 00 C0 00 00 02 88 |         (       
0010 | 00 00 00 00 02 01 F8 80                         |                 
I 307498 2024-04-28 10:09:12 - [Commands] Sending to C-18 (PLAYER) (version=GC_EP3 command=C9 flag=00)
0000 | C9 00 14 00 B4 04 00 00 1E 00 00 00 00 00 02 88 |                 
0010 | 00 01 00 00                                     |                 
I 307498 2024-04-28 10:09:12 - [Commands] Sending to C-18 (PLAYER) (version=GC_EP3 command=C9 flag=00)
0000 | C9 00 64 00 B4 18 00 00 02 00 00 00 00 00 00 00 |   d             
0010 | 07 00 00 02 00 00 05 00 00 00 00 00 14 00 16 00 |                 
0020 | 0D 00 0E 00 FF FF FF FF 1A 03 0A 00 06 00 08 00 |                 
0030 | FF FF FF FF FF FF FF FF FF FF 00 00 14 00 16 00 |                 
0040 | 0D 00 0E 00 FF FF FF FF 0A 00 06 00 08 00 FF FF |                 
0050 | FF FF FF FF FF FF FF FF 1A 03 01 00 FF FF 63 00 |               c 
0060 | 01 01 00 00                                     |                 
I 307498 2024-04-28 10:09:12 - [Commands] Sending to C-18 (PLAYER) (version=GC_EP3 command=C9 flag=00)
0000 | C9 00 64 00 B4 18 00 00 02 00 00 00 01 00 00 00 |   d             
0010 | 04 00 00 03 00 00 06 01 00 00 00 00 0F 01 1D 01 |                 
0020 | 13 01 07 01 FF FF FF FF FF FF 0B 01 0E 01 FF FF |                 
0030 | FF FF FF FF FF FF FF FF FF FF 00 01 0F 01 1D 01 |                 
0040 | 13 01 07 01 FF FF FF FF 0B 01 0E 01 FF FF FF FF |                 
0050 | FF FF FF FF FF FF FF FF FF FF 00 00 FF FF 00 00 |                 
0060 | 01 01 00 00                                     |                 
I 307498 2024-04-28 10:09:12 - [Commands] Sending to C-18 (PLAYER) (version=GC_EP3 command=C9 flag=00)
0000 | C9 00 64 00 B4 18 00 00 02 00 00 00 02 00 00 00 |   d             
0010 | 05 00 00 06 00 00 03 01 00 00 00 00 18 02 0E 02 |                 
0020 | 1A 02 FF FF FF FF FF FF FF FF 09 02 FF FF FF FF |                 
0030 | FF FF FF FF FF FF FF FF FF FF 00 02 18 02 0E 02 |                 
0040 | 1A 02 FF FF FF FF FF FF 09 02 FF FF FF FF FF FF |                 
0050 | FF FF FF FF FF FF FF FF FF FF 00 00 FF FF 00 00 |                 
0060 | 01 01 00 00                                     |                 
I 307498 2024-04-28 10:09:12 - [Commands] Sending to C-18 (PLAYER) (version=GC_EP3 command=C9 flag=00)
0000 | C9 00 64 00 B4 18 00 00 02 00 00 00 03 00 00 00 |   d             
0010 | 02 00 00 03 00 00 05 01 02 00 00 00 19 03 15 03 |                 
0020 | 13 03 12 03 FF FF FF FF FF FF 0A 03 05 03 FF FF |                 
0030 | FF FF FF FF FF FF FF FF FF FF 00 03 19 03 15 03 |                 
0040 | 13 03 12 03 FF FF FF FF 0A 03 05 03 FF FF FF FF |                 
0050 | FF FF FF FF FF FF FF FF FF FF 00 00 FF FF 00 00 |                 
0060 | 01 01 00 00                                     |                 
I 307498 2024-04-28 10:09:12 - [Commands] Sending to C-18 (PLAYER) (version=GC_EP3 command=C9 flag=00)
0000 | C9 00 64 00 B4 18 00 00 02 00 00 00 00 00 00 00 |   d             
0010 | 07 00 00 02 00 00 05 00 00 00 00 00 14 00 16 00 |                 
0020 | 0D 00 0E 00 FF FF FF FF 1A 03 0A 00 06 00 08 00 |                 
0030 | FF FF FF FF FF FF FF FF FF FF 00 00 14 00 16 00 |                 
0040 | 0D 00 0E 00 FF FF FF FF 0A 00 06 00 08 00 FF FF |                 
0050 | FF FF FF FF FF FF FF FF 1A 03 01 00 FF FF 63 00 |               c 
0060 | 01 01 00 00                                     |                 
I 307498 2024-04-28 10:09:12 - [Commands] Sending to C-18 (PLAYER) (version=GC_EP3 command=C9 flag=00)
0000 | C9 00 64 00 B4 18 00 00 02 00 00 00 01 00 00 00 |   d             
0010 | 04 00 00 03 00 00 06 01 00 00 00 00 0F 01 1D 01 |                 
0020 | 13 01 07 01 FF FF FF FF FF FF 0B 01 0E 01 FF FF |                 
0030 | FF FF FF FF FF FF FF FF FF FF 00 01 0F 01 1D 01 |                 
0040 | 13 01 07 01 FF FF FF FF 0B 01 0E 01 FF FF FF FF |                 
0050 | FF FF FF FF FF FF FF FF FF FF 00 00 FF FF 00 00 |                 
0060 | 01 01 00 00                                     |                 
I 307498 2024-04-28 10:09:12 - [Commands] Sending to C-18 (PLAYER) (version=GC_EP3 command=C9 flag=00)
0000 | C9 00 64 00 B4 18 00 00 02 00 00 00 02 00 00 00 |   d             
0010 | 05 00 00 06 00 00 03 01 00 00 00 00 18 02 0E 02 |                 
0020 | 1A 02 FF FF FF FF FF FF FF FF 09 02 FF FF FF FF |                 
0030 | FF FF FF FF FF FF FF FF FF FF 00 02 18 02 0E 02 |                 
0040 | 1A 02 FF FF FF FF FF FF 09 02 FF FF FF FF FF FF |                 
0050 | FF FF FF FF FF FF FF FF FF FF 00 00 FF FF 00 00 |                 
0060 | 01 01 00 00                                     |                 
I 307498 2024-04-28 10:09:12 - [Commands] Sending to C-18 (PLAYER) (version=GC_EP3 command=C9 flag=00)
0000 | C9 00 64 00 B4 18 00 00 02 00 00 00 03 00 00 00 |   d             
0010 | 02 00 00 03 00 00 05 01 02 00 00 00 19 03 15 03 |                 
0020 | 13 03 12 03 FF FF FF FF FF FF 0A 03 05 03 FF FF |                 
0030 | FF FF FF FF FF FF FF FF FF FF 00 03 19 03 15 03 |                 
0040 | 13 03 12 03 FF FF FF FF 0A 03 05 03 FF FF FF FF |                 
0050 | FF FF FF FF FF FF FF FF FF FF 00 00 FF FF 00 00 |                 
0060 | 01 01 00 00                                     |                 
E 307498 2024-04-28 10:09:12 - [C-18] Episode 3 engine returned an error: basic_string::_M_replace_aux
E 307498 2024-04-28 10:09:12 - [C-18] Saved partial battle record as system/ep3/battle-records/exc.1714298952513274.mzrd
W 307498 2024-04-28 10:09:12 - [Server] Error processing client command: basic_string::_M_replace_aux
I 307498 2024-04-28 10:09:12 - [Server] Client disconnected: C-18
```

**Additional context**
Partial battle recording: [exc.1714298952513274.mzrd.zip](https://github.com/fuzziqersoftware/newserv/files/15141750/exc.1714298952513274.mzrd.zip)

**Comment by fuzziqersoftware** [comment] 2024-12-14 18:03
I haven't been able to reproduce this; I suspect it has been fixed by some other change in the time since this issue was opened.

**Closed by fuzziqersoftware** 2024-12-14 18:03 UTC
