### ISSUE TITLE
[Blue Burst] Players who aren't the monster's killer wont get any EXP

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#234] opened 2023-11-26 15:20 UTC
In a 2 player party if Player 2 "Tags" an enemy by hitting it a few times without killing it and let's Player 1 finish them off, Player 1 gets the exp but Player 2 wont get any exp from the defeated monster.

Video

https://github.com/fuzziqersoftware/newserv/assets/5244595/65651b22-ab6a-44d9-9d07-97170bf2ed74

**Comment by fuzziqersoftware** [comment] 2023-11-26 22:59
This may be working as intended - a tag has to do a nonzero amount of damage to be counted for purposes of EXP, so I would expect the Level 1 player to get no EXP here. Does it work if the tagger does a nonzero amount of damage?

**Comment by nolrinale** [comment] 2023-11-26 23:14
I just ran the same test with both 0 dmg and >0 dmg on PSO GC, it works as intended the Player 2 gets exp as long is not a MISS.

It should be the same on BB as the game is clearly displaying the earned EXP in both screens too.

**Comment by fuzziqersoftware** [comment] 2023-11-27 00:23
This is fixed by ea83935d.

**Closed by fuzziqersoftware** 2023-11-27 00:23 UTC

**Comment by ShiftaDeband** [comment] 2023-11-27 01:37
Forgive my memory here, but wasn’t this changed in PSOBB due to things like the Recobox EXP trick?

https://www.pso-world.com/forums/showthread.php?69994-Recobox-trick-no-longer-working-on-PSO-BB

I’m not sure if that was a change made because of this (or trying to mob tag, essentially). 

I can test this and file a separate bug report later if this isn’t working as intended, but making a note for now. It may also just be entirely different functionality.

**Comment by fuzziqersoftware** [comment] 2023-11-27 01:46
My understanding (now) is that the >0 damage requirement change only applied to EXP-stealing weapons, not kills. The client sends a 6xC8 command if it believes it deserves EXP from a kill, and the client still sends that command even if the player tagged an enemy without doing any damage. I haven't yet tested if the client also sends 6xC6 (the EXP-steal command) if the attack does no damage, however.

**Comment by nolrinale** [comment] 2023-11-27 07:38
Just did a quick test on a Recobox, equiped the lv 3 char with a Master's Autogun and began to just shoot at the box with the EX attack, what I noticed is that it was able to land a hit with 0 but at the same time a MISS appeared overlapped on top of it so I assume this is the mitigation that was added to fix it.

Heres a demonstration video

https://github.com/fuzziqersoftware/newserv/assets/5244595/60edb637-1f7c-47a2-bedb-e088bfc222a7



Either way since I'm not entirely sure how to look for the command heres the log of that session too 
[MasterStealTestRecobox.txt](https://github.com/fuzziqersoftware/newserv/files/13471140/MasterStealTestRecobox.txt)

**Comment by fuzziqersoftware** [comment] 2023-11-27 08:37
From that log snippet, it looks like the client doesn't send 6xC6 commands if an EXP-stealing attack does no damage, so the existing behavior should now be correct.
