### ISSUE TITLE
Configuring the server to accept BBA tapserver connections from Dolphin

### ISSUE THREAD

**Issue by chronicvagrant** [fuzziqersoftware/newserv#445] opened 2024-03-23 22:17 UTC
Hello! My brother and I were hoping we'd be able to set up our own server to accept connections from the new tapserver version of the BBA adapter in Dolphin, specifically to play Episodes 1 & 2. We understand that this new version of the BBA adapter should reduce or eliminate the random FSODs we would see every time we played using BBA HLE.

-We're setting it up to run on Windows
-Our understanding is we don't have to download anything else, Newserv and Dolphin with the tapserver BBA is all we need
-The hosting PC is DMZ'd, because we couldn't forward port 53
-As mentioned above, we have been able to connect and play to our own server using the BBA HLE. I can host the server and connect to it over my LAN by setting BBA HLE to use the host PC's LAN address, and he can connect to it remotely from his house by setting BBA HLE to use my public IP.

We're not sure what we're doing wrong with setting it up to accept the tapserver connection. We can't get any kind of connection to go through - local (same machine), LAN (1 host PC, 1 client PC, same LAN), or remote. No matter what we try, it always ends with error 015, unable to obtain IP address from DHCP.

First we tried setting the BBA tapserver in Dolphin to use the host PC's LAN address/port, and we tried using public address/port, neither worked. We tried using various ports for the login servers (9100, 9103, 5100, plus more including custom ports) as well as 53.

Then we wondered if we needed to change something in Newserv's settings, maybe it had to do with the stack clients settings. For IPStackListen, if we set it to ["/tmp/dolphin-tap"] to try to connect from the same machine, Newserv will crash on startup saying something like "no such location or file exists". So we've been leaving that default/blank.

So then we started trying different address/port combinations in PPPStackListen, and trying to set Dolphin's BBA tapserver to match it. We tried ["127.0.0.1:5059"] to connect from the same machine, didn't work. We tried connecting from a different machine on the same LAN and using the host LAN address+ different ports, none of those work either. In some cases the server will appear to detect a connection attempt but it always fails (error 015, unable to obtain IP address from DHCP). Any ideas what we're doing wrong? What should we be doing to set this up properly?
![newserv tapserver error window](https://github.com/fuzziqersoftware/newserv/assets/107323044/858049ec-68eb-4adf-90cc-8b1e2d064afc)

**Comment by Matt-Swift** [comment] 2024-03-23 22:21
IPStackListen should be set to the local IP address of the server with an arbitrary port. This is how I have it setup on my server and people are able to connect.

So for example:

`"IPStackListen": ["172.26.3.79:9501"],`

You then set up Dolphin to use this address and port.

I admit that I don't have your current set up, so it's possible some more network things need to be configured.

**Comment by chronicvagrant** [comment] 2024-03-23 22:32
> IPStackListen should be set to the local IP address of the server with an arbitrary port. This is how I have it setup on my server and people are able to connect.
> 
> So for example:
> 
> `"IPStackListen": ["172.26.3.79:9501"],`
> 
> You then set up Dolphin to use this address and port.
> 
> I admit that I don't have your current set up, so it's possible some more network things need to be configured.

Thanks for the quick reply. We have tried that, in fact the image I posted above where it says "Listening on TCP interface" you can see the host PC's LAN address and the port we tried (9501), and then we tried to connect with Dolphin from another PC on the same LAN, with 192.168.1.111:9501 entered into Dolphin's tapserver BBA to match.

Again, we tried several different ports too, even 9501 because we saw you had used that for the Ragol server.

Two questions for you:
1. In your settings, is IPStackListen left blank?

2. You didn't have to configure or define that port (9501) anywhere else in Newserv's settings either? We had wondered if anything needed to be added to the section where ports 5100-5124, etc are defined.

**Comment by Matt-Swift** [comment] 2024-03-23 22:35
1. No
2. Nope, just forwarded on the firewall.

I'm suspecting a Windows firewall issue here... been a while since I used it, but it's possible you might need to do some inbound and outbound rules, or even perhaps just unblock the newserv executable.

**Comment by fuzziqersoftware** [comment] 2024-03-23 22:38
The tapserver modem and BBA use different protocols that are not compatible with each other. If you're using the tapserver BBA (not modem), you should use IPStackListen in config.json; if you're using the tapserver modem, you should use PPPStackListen. It looks like you've set up PPPStackListen instead of the IPStackListen in your config; if you've set up IPStackListen, the log message during startup should say T-IPS-XXXX instead of T-PPPS-XXXX.

**Comment by chronicvagrant** [comment] 2024-03-23 22:40
> 1. No
> 2. Nope, just forwarded on the firewall.
> 
> I'm suspecting a Windows firewall issue here... been a while since I used it, but it's possible you might need to do some inbound and outbound rules, or even perhaps just unblock the newserv executable.

I've got Newserv set as an exception in Windows Firewall, but I can look to see if I missed anything there. The host PC is in the router's DMZ also, not ideal but we couldn't forward port 53 so there wasn't much choice. The connection issues are only happening with the tapserver BBA, if we use the old HLE BBA, I can connect to the host PC from other PCs on my LAn, and my brother can connect remotely from his house.

**Comment by chronicvagrant** [comment] 2024-03-23 22:43
> The tapserver modem and BBA use different protocols that are not compatible with each other. If you're using the tapserver BBA (not modem), you should use IPStackListen in config.json; if you're using the tapserver modem, you should use PPPStackListen. It looks like you've set up PPPStackListen instead of the IPStackListen in your config; if you've set up IPStackListen, the log message during startup should say T-IPS-XXXX instead of T-PPPS-XXXX.

Yes, we're trying to use the BBA, so let me try that. It's expecting the same thing I assume, IPStackListen should be set with the address/port? Going to give it a shot.

**Comment by chronicvagrant** [comment] 2024-03-23 22:49
> The tapserver modem and BBA use different protocols that are not compatible with each other. If you're using the tapserver BBA (not modem), you should use IPStackListen in config.json; if you're using the tapserver modem, you should use PPPStackListen. It looks like you've set up PPPStackListen instead of the IPStackListen in your config; if you've set up IPStackListen, the log message during startup should say T-IPS-XXXX instead of T-PPPS-XXXX.

Yes, that worked! It never occurred to us to try that. I set "IPStackListen" to use the host PC LAN address + port 9501, and I can connect to it just fine from the other PC on the LAN. Thanks very much Now we'll see if we can get a remote connection to go through.

**Comment by chronicvagrant** [comment] 2024-03-23 23:03
> IPStackListen should be set to the local IP address of the server with an arbitrary port. This is how I have it setup on my server and people are able to connect.
> 
> So for example:
> 
> `"IPStackListen": ["172.26.3.79:9501"],`
> 
> You then set up Dolphin to use this address and port.
> 
> I admit that I don't have your current set up, so it's possible some more network things need to be configured. I have the appropriate ports forwarded on my VPS firewall, though this shouldn't be necessary for a local network, though maybe your firewall is blocking the ports entirely on the network?
> 
> As an aside, PSO should also have automatic settings in the provider options, nothing manual.

I didn't catch it at first but you provided the correct answer. We had only been trying PPPStackListen when the solution for the BBA adapter is to use IPStackListen. Apologies, and thanks for your help!

**Comment by chronicvagrant** [comment] 2024-03-24 02:14
The remote connection worked fine, everything is working like it should. So just a quick recap for anyone else that might end up looking for help:

In Newserv's configuration:
"LocalAddress": Enter the host PC's LAN address (assigned to the PC by your router)
"ExternalAddress": Enter the public IP address (assigned to you by your ISP)
"IPStackListen": ["address:port"], This is for BBA tapserver connections from Dolphin. Use the host PC's LAN address + unblocked port number of your choosing. I just went with 9501. So it would look like:
"IPStackListen": ["192.168.1.111:9501"],

I'm only interested in BBA connections so I didn't bother setting PPPStackListen for modem connections, which I also understand would require a little extra internal setup for PSO's network settings for the user.

With the above settings, to connect with Dolphin from another PC on my LAN, I enter my LAN address + port in Dolphin's BBA tapserver (192.168.1.111:9501)

For my brother to connect to my server remotely, in Dolphin's BBA tapserver he enters my public IP address plus the same port number.

**Comment by nolrinale** [comment] 2024-03-31 15:13
@chronicvagrant if the issue is resolved, please close this ticket

**Closed** 2024-03-31 16:15 UTC
