### ISSUE TITLE
[Blue Burst] Frequent disconnects when playing in a small group

### ISSUE THREAD

**Issue by ValKilmersCareer** [fuzziqersoftware/newserv#161] opened 2023-10-31 05:48 UTC
I was playing with 3 other people, and after about an hour we began to have increasingly frequent disconnects. It was just 3 of us at one point, and the error messages I found read something like "item does not exist". It doesn't make sense because it would happen during combat or while one of us was going through a menu or just picking something up. 2 of us did use the item creation command several times, so I'm wondering if that could be part of it.

**Comment by fuzziqersoftware** [comment] 2023-10-31 05:51
It's likely that the clients' item states went out of sync with the server's item state. This happens sometimes because BB support is still a work in progress... if you have a full log of the game that you could upload here (everything that appeared in the server's console output), that would be very helpful in fixing these kinds of issues.

**Comment by Matt-Swift** [comment] 2023-11-13 16:30
I got a game log for this one, although it's a solo player. Someone logged on during this so there's some patch server junk in the middle.

[ItemNotPresentBB.txt](https://github.com/fuzziqersoftware/newserv/files/13337523/ItemNotPresentBB.txt)

**Comment by fuzziqersoftware** [comment] 2023-11-16 02:17
There were multiple bugs here which could have caused these problems:
* The server generated item IDs for items in a shop before they were purchased. The client doesn't actually use these IDs, so this causes the next item ID value to go out of sync between the server and client for the player who opened the shop. During a normal game, this doesn't actually break anything, but if that player leaves the game and another player joins in the same slot, the new player will have incorrect IDs on their inventory items.
* The server did not account for the client "wasting" an item ID when an item is tekked. This causes effects similar to the above bug - if the player leaves and someone else joins in that slot, their inventory items will be broken.
* The server did not account for duplicate pick up requests. If a player tries to pick up the same item multiple times quickly, the client sends multiple requests to pick up the same item. The server should just ignore all but the first request, which it wasn't doing. This was the cause of the failure in the log Matt posted.

All of these have been fixed. I'm going to close this issue, but there may still be item-related bugs on BB. If you find any, please feel free to open another issue.

**Closed by fuzziqersoftware** 2023-11-16 02:17 UTC
