### ISSUE TITLE
[Blue Burst] Item not present client command error while doing EP2 Stage1 CMODE

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#317] opened 2024-01-04 00:24 UTC
Created a party of 4, died several times spawned lots of tomestones around the area, retried the same challenge like 5 times in a row, until in one of the games an enemy was killed and the Player1 client got disconnected with Error 100 and an error in the console stating:

```
0010 | 1B 6F E7 C0 6F FE DC 40                         |  o  o  @        
I 40072 2024-01-04 01:15:00 - [Commands] Sending to C-16 (KAREN) (version=BB command=0060 flag=00000000)
0000 | 18 00 60 00 00 00 00 00 4C 04 01 00 10 5F 0C 00 |   `     L    _  
0010 | 1B 6F E7 C0 6F FE DC 40                         |  o  o  @        
I 40072 2024-01-04 01:15:01 - [Commands] Received from C-17 (RUPIKA) (version=BB command=0060 flag=00000000)
0000 | 14 00 60 00 00 00 00 00 29 03 00 00 4C 00 01 00 |   `     )   L   
0010 | 01 00 00 00                                     |                 
W 40072 2024-01-04 01:15:01 - [Server] Error processing client command: item not present
I 40072 2024-01-04 01:15:01 - [Server] Client disconnected: C-17 on fd 39
I 40072 2024-01-04 01:15:01 - [Lobby:00000015:FloorItems:00] Deleted 0 inaccessible items
I 40072 2024-01-04 01:15:01 - [Lobby:00000015:FloorItems:01] Deleted 0 inaccessible items

```

Full log of the session, the log starts with starting the server and logging the 4 clients then heading directly to cmode

[4PlayerEP2CmodeStage1ClientCommandError100.txt](https://github.com/fuzziqersoftware/newserv/files/13824584/4PlayerEP2CmodeStage1ClientCommandError100.txt)

**Comment by fuzziqersoftware** [comment] 2024-01-04 17:27
This was caused by grave recovery items not consuming an item ID on the server side. The client expects them to consume one of the leader's item IDs, so if a challenge is retried after that, the leader's starting inventory item IDs go out of sync. This is fixed by 1449bf09.

**Closed by fuzziqersoftware** 2024-01-04 17:27 UTC
