### ISSUE TITLE
[PC] Constant disconnects when playing in groups

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#153] opened 2023-10-24 20:53 UTC
In the past few days, people have been playing online in groups and within about 5 minutes of actively playing, clients will send the 04 00 05 00 command randomly with no known trigger. There is no known pattern from any of the logs, but I can provide extensive logs of games if wanted.

Once this occurs, the client will not actually disconnect, but stop sending commands other than more 04 00 05 00 commands and 04 00 1D 00 commands when responding to pings.

The player would have to close the client themselves for it to actually disconnect from the server.

I had a group of players use the client I had provided on Sylverant, and they did not run into any issues there, whether item desyncs or sending disconnection commands to the server.

I will post logs relatively shortly.

**Comment by fuzziqersoftware** [comment] 2023-10-26 03:21
At least two major causes of this issue have been fixed; however, I'm not confident yet that there aren't any remaining issues. I'll leave this open for now, so please comment if the issue continues.

**Comment by Matt-Swift** [comment] 2023-10-28 19:51
It's mostly stable now, but there have been a couple of other errors. In both cases, the player was the leader, and they said that they were not doing any specific in both instances (things like scrolling through inventory or attacking):
```
I 853734 2023-10-28 19:02:12 - [Commands] Received from C-1BD (Ysmir) (version=PC command=62 flag=00)
0000 | 1C 00 62 00 60 06 00 00 03 30 A8 00 56 31 AC 44 |   b `    0  V1 D
0010 | 26 C5 88 C4 3C 00 01 00 03 00 80 3F             | &   <      ?    
W 853734 2023-10-28 19:02:12 - [Server] Error processing client command: invalid tool class
I 853734 2023-10-28 19:02:12 - [Server] Client disconnected: C-1BD on fd 39
```
```
I 853734 2023-10-28 19:49:11 - [Commands] Received from C-1C4 (Ysmir) (version=PC command=62 flag=00)
0000 | 1C 00 62 00 60 06 00 00 04 0D 84 01 00 00 57 43 |   b `         WC
0010 | 00 10 06 C5 2D 00 00 00 04 AC 4D E9             |     -     M     
I 853734 2023-10-28 19:49:11 - [ItemCreator] Enemy type: D
I 853734 2023-10-28 19:49:11 - [ItemCreator] Enemy spec 00500000 did not produce item 01011C
I 853734 2023-10-28 19:49:11 - [ItemCreator] Rare drop not chosen; item class determinant is 1; item class is 4
W 853734 2023-10-28 19:49:11 - [Server] Error processing client command: invalid tool class
I 853734 2023-10-28 19:49:11 - [Server] Client disconnected: C-1C4 on fd 39
```
If you need more information around these I can go find them.

**Comment by Matt-Swift** [comment] 2023-11-06 09:28
Moving #171 into here (forgot this existed):

Player sent a 04 00 05 00 disconnect command at the end of Stage 2 Challenge, didn't seem to be any specific cause as they stopped in the middle of the room.

[04 00 05 00 1C2.zip](https://github.com/fuzziqersoftware/newserv/files/13257458/04.00.05.00.1C2.zip) - This is a somewhat large log of the full game up to the final disconnect command sent, about 30 minutes or so of gameplay and like 370,000 lines.

**Comment by fuzziqersoftware** [comment] 2023-11-21 19:52
I believe this has been fixed (but as always, please reopen if you see this again). The cause is explained by this recently-added comment:

    // There is a bug in the client that can cause desync between players' item IDs
    // if the 6x6D command is sent too quickly. Under normal operation, the client
    // keeps track of the next item ID to be assigned for items it creates, and uses
    // that to assign item IDs to its inventory items when it's done loading (just
    // before it sends the 6F command). The loading process triggered by the 64
    // (game join) command resets these next item ID variables to their default
    // values, and the 6x6D command sent by the leader resets them again to match
    // the corresponding variables in the leader's item state. However, the loading
    // process doesn't actually start until the next frame after the 64 command is
    // received, so if the 6x6D command is received on the same frame as the 64
    // command, it will set the next item ID variables correctly, and the loading
    // process will then clear all of them on the next frame. The client will then
    // assign its own inventory item IDs based on the default base item ID, which
    // will result in incorrect IDs if another player had previously been in the
    // game in the same slot (since the leader's next item ID for the joining player
    // will not match the default value). Fortunately, the game processes commands
    // in two phases: first, it receives as much data as possible, then it processes
    // as many commands as possible. So, to prevent this bug, we delay all commands
    // after a 64 is sent until the client responds to a ping command (sent
    // immediately after the 64 command), which ensures that the 64 and 6x6D
    // commands cannot be processed on the same frame.

**Closed by fuzziqersoftware** 2023-11-21 19:52 UTC
