### ISSUE TITLE
[Episode 3] std::bad_alloc during a DEF phase

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#467] opened 2024-04-22 22:10 UTC
**Describe the bug**
When a player was playing earlier, they were fighting Castor and unfortunately ended up causing the above error when attacking.

Situation was: Orland with Double Cannon.

![image](https://github.com/fuzziqersoftware/newserv/assets/33199242/83bdd240-731c-47ed-9d6b-720af9210138)

**To reproduce**
Don't know exact reproduction steps other than the above screenshot.

**Game version(s) (choose one or more of the following):**
GC Ep3

**Server log output**
```
I 254608 2024-04-22 21:27:03 - [Commands] Received from C-CE (LiquidMagic) version=GC_EP3 command=CA flag=00)
0000 | CA 00 18 00 B3 05 01 00 28 00 00 80 00 00 00 EC |         (       
0010 | 00 00 00 00 01 01 E8 40                         |        @        
I 254608 2024-04-22 21:27:03 - [Commands] Sending to C-CE (LiquidMagic) version=GC_EP3 command=C9 flag=00)
0000 | C9 00 14 00 B4 04 00 00 1E 00 00 00 00 00 00 EC |                 
0010 | 00 01 00 00                                     |                 
I 254608 2024-04-22 21:27:03 - [Commands] Sending to C-CE (LiquidMagic) version=GC_EP3 command=C9 flag=00)
0000 | C9 00 64 00 B4 18 00 00 02 00 00 00 00 00 00 00 |   d             
0010 | 05 00 01 02 01 00 08 00 02 00 00 00 01 00 16 00 |                 
0020 | 14 00 15 00 FF FF FF FF FF FF 0F 00 03 00 FF FF |                 
0030 | FF FF FF FF FF FF FF FF FF FF 00 00 01 00 16 00 |                 
0040 | 14 00 15 00 FF FF FF FF 0F 00 03 00 FF FF FF FF |                 
0050 | FF FF FF FF FF FF FF FF FF FF 00 00 FF FF 00 00 |                 
0060 | 00 00 00 00                                     |                 
I 254608 2024-04-22 21:27:03 - [Commands] Sending to C-CE (LiquidMagic) version=GC_EP3 command=C9 flag=00)
0000 | C9 00 64 00 B4 18 00 00 02 00 00 00 01 00 00 00 |   d             
0010 | 01 00 02 01 02 00 00 01 00 00 00 00 19 01 0B 01 |                 
0020 | 0A 01 04 01 1C 01 FF FF FF FF FF FF FF FF FF FF |                 
0030 | FF FF FF FF FF FF FF FF FF FF 00 01 19 01 0B 01 |                 
0040 | 0A 01 04 01 1C 01 FF FF FF FF FF FF FF FF FF FF |                 
0050 | FF FF FF FF FF FF FF FF FF FF 00 00 FF FF 00 00 |                 
0060 | 00 00 00 00                                     |                 
I 254608 2024-04-22 21:27:03 - [Commands] Sending to C-CE (LiquidMagic) version=GC_EP3 command=C9 flag=00)
0000 | C9 00 64 00 B4 18 00 00 02 00 00 00 00 00 00 00 |   d             
0010 | 05 00 01 02 01 00 08 00 02 00 00 00 01 00 16 00 |                 
0020 | 14 00 15 00 FF FF FF FF FF FF 0F 00 03 00 FF FF |                 
0030 | FF FF FF FF FF FF FF FF FF FF 00 00 01 00 16 00 |                 
0040 | 14 00 15 00 FF FF FF FF 0F 00 03 00 FF FF FF FF |                 
0050 | FF FF FF FF FF FF FF FF FF FF 00 00 FF FF 00 00 |                 
0060 | 00 00 00 00                                     |                 
I 254608 2024-04-22 21:27:03 - [Commands] Sending to C-CE (LiquidMagic) version=GC_EP3 command=C9 flag=00)
0000 | C9 00 64 00 B4 18 00 00 02 00 00 00 01 00 00 00 |   d             
0010 | 01 00 02 01 02 00 00 01 00 00 00 00 19 01 0B 01 |                 
0020 | 0A 01 04 01 1C 01 FF FF FF FF FF FF FF FF FF FF |                 
0030 | FF FF FF FF FF FF FF FF FF FF 00 01 19 01 0B 01 |                 
0040 | 0A 01 04 01 1C 01 FF FF FF FF FF FF FF FF FF FF |                 
0050 | FF FF FF FF FF FF FF FF FF FF 00 00 FF FF 00 00 |                 
0060 | 00 00 00 00                                     |                 
W 254608 2024-04-22 21:27:03 - [Server] Error processing client command: std::bad_alloc
I 254608 2024-04-22 21:27:03 - [Server] Client disconnected: C-CE
```
**Additional context**
I'll get more of the game log later.

**Comment by Matt-Swift** [comment] 2024-04-26 11:16
Got the full game log, it's here: [bad_alloc.txt](https://github.com/fuzziqersoftware/newserv/files/15129804/bad_alloc.txt)

There's a lot of other server nonsense going on here.

**Comment by fuzziqersoftware** [comment] 2024-12-14 18:03
I haven't been able to reproduce this; I suspect it has been fixed by some other change in the time since this issue was opened.

**Closed by fuzziqersoftware** 2024-12-14 18:03 UTC
