### ISSUE TITLE
[Blue Burst] Cannot get past patch screen without patch-bb contents, and cannot startup server with them

### ISSUE THREAD

**Issue by RaikohKatsushiro** [fuzziqersoftware/newserv#448] opened 2024-03-24 23:24 UTC
**Bug(s) and how to reproduce:**
I extracted the contents of newserv release v2024-03-14, replaced LocalAddress and ServerName, ran the server.
Gamecube PSO Ep1&2/3 connnect fine using Dolphin (HLE BBA). **PSO Blue Burst however is stuck on patch screen**. Background animation is moving, but no progress is ever made or any progress bar is shown at all. If I close the server at this point, I immediately get error 903 on client, indicating there was a successful connection of some sort.

Then I add map*.dat and data.gsl files into patch-bb/data folder and restart the server. **Now the server crashes on startup**. I've tried using files from multiple PSO BB clients (including those shared to me by an Ephinea staff member), and the result is always the same. See last logs before crash below (dump file is in attachment):
```
I 793 2024-03-24 13:27:24 - [Config] Loading tool table
I 793 2024-03-24 13:27:24 - [Config] Loading weapon tables
I 793 2024-03-24 13:27:24 - [Config] Loading tekker adjustment table
0 [main] newserv 793 cygwin_exception::open_stackdumpfile: Dumping stack trace to newserv.exe.stackdump
```
If I remove data.gsl from patch directory, server now runs properly once more, but I get stuck on patch screen again.

**Additional context:**
Running server and client on same machine, running on Windows 10. Tried running server on both "Command Prompt" and "Windows PowerShell", with same results. Let me know if additional system information is needed.
I deleted JSON cache on patch-bb in-between trying different .dat files.
I just tested on the latest release (v2024-03-24) and issue remains.
[Reddit thread](https://www.reddit.com/r/PSO/comments/1bm8lxw/comment/kwbc994/?context=3) where I recently asked this same question, if relevant.

Thank you!
[newserv.exe.stackdump.txt](https://github.com/fuzziqersoftware/newserv/files/14737148/newserv.exe.stackdump.txt)

**Comment by nolrinale** [comment] 2024-03-25 00:13
When you reach the patch screen for the first time in a freshly installed client it will take a while for the client to check each file vs the copies in the server so it will look like it's stalled in this screen, just let it run for a little while more and eventually you will see the progress bars working and downloading the missing files, then once finished just restart the client and run the game as usual it should connect without issues.

maybe the check speed can be improved server side but I think this is just a client limitation its just how it works but @fuzziqersoftware can explain better

**Comment by fuzziqersoftware** [comment] 2024-03-25 03:15
This is correct; the patch screen will hang for a while the first time, because it can take a while for the server to populate its index of checksums. These checksums are computed lazily (that is, they are not computed until the server needs them), which is why they block the patch process the first time. After that, though, the checksums are saved to a file and not recomputed from scratch, so subsequent patch sessions should be fast.

It's unfortunate that in Cygwin, we just get a stackdump when an exception is thrown and not an error message. On Linux and macOS, the error message would appear here, and it would tell you what went wrong. I've updated the most recent release with a new build that shows the error message on Windows, so you can see what the problem is.

Just from your report, however, it looks like an exception is being thrown during late-phase configuration. Probably something in your configuration file doesn't match the game data; it could be the case that an item name used in config.json refers to an item that doesn't exist (or has a different name) in the data files you're using in patch-bb. The fix might be as simple as adding the unitxt files to patch-bb as well (since there may be unitxt files in data.gsl that are missing item names).

**Comment by RaikohKatsushiro** [comment] 2024-03-25 10:24
Thanks for the explanation on first-time through patch screen. I left it there for at least 10 minutes so I assumed it was stuck. I'll leave it for longer and check again.

As for the server crash, I'm sharing the last logs using the new release below. As for adding the unitxt files, could you please explain in detail what I should do, if still applicable given this error? I do wonder though, considering both client and server are basically clean installs, why a mismatch is happening. Did I make a mistake along the way?

Thanks!

```
I 1112 2024-03-25 10:10:23 - [Config] Loading tekker adjustment table
I 1112 2024-03-25 10:10:23 - [Lobby:14] Deleted
I 1112 2024-03-25 10:10:23 - [Lobby:13] Deleted
I 1112 2024-03-25 10:10:23 - [Lobby:12] Deleted
I 1112 2024-03-25 10:10:23 - [Lobby:11] Deleted
I 1112 2024-03-25 10:10:23 - [Lobby:10] Deleted
I 1112 2024-03-25 10:10:23 - [Lobby:F] Deleted
I 1112 2024-03-25 10:10:23 - [Lobby:E] Deleted
I 1112 2024-03-25 10:10:23 - [Lobby:D] Deleted
I 1112 2024-03-25 10:10:23 - [Lobby:C] Deleted
I 1112 2024-03-25 10:10:23 - [Lobby:B] Deleted
I 1112 2024-03-25 10:10:23 - [Lobby:A] Deleted
I 1112 2024-03-25 10:10:23 - [Lobby:9] Deleted
I 1112 2024-03-25 10:10:23 - [Lobby:8] Deleted
I 1112 2024-03-25 10:10:23 - [Lobby:7] Deleted
I 1112 2024-03-25 10:10:23 - [Lobby:6] Deleted
I 1112 2024-03-25 10:10:23 - [Lobby:5] Deleted
I 1112 2024-03-25 10:10:23 - [Lobby:4] Deleted
I 1112 2024-03-25 10:10:23 - [Lobby:3] Deleted
I 1112 2024-03-25 10:10:23 - [Lobby:2] Deleted
I 1112 2024-03-25 10:10:23 - [Lobby:1] Deleted
E 1112 2024-03-25 10:10:23 - Top-level exception (runtime_error): cannot parse item description "Tablet" (as text: item not found: tablet) (as data: data is too short)
      0 [main] newserv 1112 cygwin_exception::open_stackdumpfile: Dumping stack trace to newserv.exe.stackdump
```

**Comment by nolrinale** [comment] 2024-03-25 11:58
Copy the `unitxt_e.prs` and `unitxt_j.prs` located in `system/text-sets/bb-v4` into your patch server folder and it should work

**Comment by KrisanThyme** [comment] 2024-03-25 16:33
I seem to also be having the same issue as Raikoh, where the client appears to just sit at the Patch screen with nothing happening. There's nothing going on in the server console either, so it's very difficult to discern exactly what the problem is.. I've left the client sitting like this for a solid half hour after reading nolrinale's response, but it never progresses past this point. (I can't imagine it should take THAT long anyway..)

**Comment by nolrinale** [comment] 2024-03-25 19:22
Is the client installed in My Documents or Programs folder? Let's try installing the client in a folder directly located in the root for example here -> C:\PSOBB

**Comment by KrisanThyme** [comment] 2024-03-25 19:27
Thanks for the response.
Unfortunately no, I do not have it in either of those locations. (I know enough *not* to do that, writes permissions and all that) But just for the sake of it, I did try putting it in the root of one of my drives under simply "PSOBB" and still the same thing..

**Comment by nolrinale** [comment] 2024-03-25 19:33
What client is this? Is it the original Tethealla Client without any special patch applied to it besides the host/port? did you modified the version string of the title screen?

**Comment by KrisanThyme** [comment] 2024-03-25 19:40
It is in fact the original Teth Client, yes. I did not change anything other than the IP address and version string - does the version string matter? As an aside, I just tested an older release [(2024-02-10)](https://github.com/fuzziqersoftware/newserv/releases/tag/v2024-02-10) specifically, and *that* one seems to work just fine. Neither the latest nor second to latest build however get past the frozen patch screen.

**Comment by nolrinale** [comment] 2024-03-25 19:48
Lets try with the original untouched sega client
https://archive.org/details/psobb_jp_setup_12511_20240109/

Delete everything you had up to this point, then install this client, once the setup is done go to the psobb folder and delete the files `gameguard.des` and `psobb.pat`, then copy all the *.map and gsl files from the data folder into your patch server.

Now you just need to prepare the exe, this time you will modify the TethExe only the ipadress to point to your server and nothing else.

replace the PsoBB.exe in the client folder with your newly patched one and start the game, it should start completely in japanese (this is normal is an unpatched one) but should at least allow you to login and play.



This is exactly the same setup I have here in both Windows 10 and Linux (via stock wine) if it doesnt work then we will have to check your computer or windows defender or something else.

**Comment by KrisanThyme** [comment] 2024-03-25 19:59
Tragically no dice. I installed the fresh JP client, removed the files you instructed me to remove, copied over the map and gsl files and so forth.. copied over a fresh Teth exe and.. same thing. Frozen on the patch screen. The [(2024-02-10)](https://github.com/fuzziqersoftware/newserv/releases/tag/v2024-02-10) release does work for me though, mysteriously.. so maybe I'll just have to settle on that build for now. I can't imagine what the difference would be since I checked the commits myself and see nothing that should interfere like this..

**Comment by nolrinale** [comment] 2024-03-25 20:00
is there a way you can run the server software via linux? even if its just a VM can spin up a simple Debian VM and install the whole server there and discard anythin related to cygwin/windows being stupid ?

**Comment by nolrinale** [comment] 2024-03-25 20:06
I run my main sever on debian is very simple to use install the super basic one without desktop environment, just follow the linux instructions in the readme and you should be good to go.

Let us know if it works that way, at this point you have the cleanest environment ready to play so we can discard client issues.

**Comment by KrisanThyme** [comment] 2024-03-25 21:26
Haven't gotten around to setting up a unix server just yet.. but thought I'd throw this out there.
I built the latest source code myself, same issue. Built version [(2024-02-10)](https://github.com/fuzziqersoftware/newserv/releases/tag/v2024-02-10) using the same environment and.. it works, just like the prebuilt one does. Given the client, build environments, and etc.. do not change.. I can only assume a commit between then and now is the culprit. *Which* commit I haven't narrowed down yet, unfortunately..

For added reference, the patch screen responds instantly with version [(2024-02-10)](https://github.com/fuzziqersoftware/newserv/releases/tag/v2024-02-10), and the server console also changes to reflect this. Version [(2024-03-14)](https://github.com/fuzziqersoftware/newserv/releases/tag/v2024-03-14) and Version [(2024-03-24)](https://github.com/fuzziqersoftware/newserv/releases/tag/v2024-03-24) however never update the server console when the patch screen comes up, and the welcome message never shows. It's almost like it's never fully establishing a connection, or that it's waiting for a response that never arrives.

**Comment by MrPolarburr** [comment] 2024-03-25 22:18
I am running into this issue as well... I am on Windows 10 and when using the latest release [2024-03-24](https://github.com/fuzziqersoftware/newserv/releases/tag/v2024-03-24) I can't get past the patch screen as it just sits there with no errors. I also downloaded the fresh client and took the steps described above to make it as basic as possible but it still wouldn't work. But just like KrisanThyme, I seem to have no issues running on [2024-02-10](https://github.com/fuzziqersoftware/newserv/releases/tag/v2024-02-10).

**Comment by RaikohKatsushiro** [comment] 2024-03-25 22:29
I can also confirm that, with the latest version, even when leaving the client on patch screen for 3 whole hours, no progress is made. When using version [2024-02-10](https://github.com/fuzziqersoftware/newserv/releases/tag/v2024-02-10) as per KrisanThyme's suggestion, the patching happens in about a second. And after restarting the client, I can now connect and play. So, it does seem to be some issue on the latest version, on specific environments, possibly related to Windows 10 or the Windows build.

(although after patching, interface is now in Japanese for some reason, but I can probably figure this out later; do feel free to drop me a one-liner telling me why this might have happened and how to fix it :)

**Comment by nolrinale** [comment] 2024-03-25 23:11
As ive said before with the original client, the interface is in japanese because thats the real language of PSOBB, the tethealla client had a bunch of modded files that forcibly changed the UI to english but in an incomplete form, it is possible to enable the proper english mode if you follow the guide in the `notes` folder but for the testing we are currently doing is not necessary as you just cannot acess the game at all yet.

The fact none of you can get past the patch screen, is something that must be tackled first and I'm afraid I already ran out of ideas, so maybe @fuzziqersoftware can chip in and offer another alternative. 

I believe it must be something in the window environment messing things up thats why I really really recommend to test on Linux just to discard a possible bug with the server software, please set up the VM with Debian and try again.

**Comment by fuzziqersoftware** [comment] 2024-03-26 00:41
Can someone upload the full log of what the server outputs, from startup until the client hangs at the patch screen? I suspect the issue is caused by libevent not working well with Windows threads, since the patch server was moved to a separate thread recently.

**Comment by KrisanThyme** [comment] 2024-03-26 02:03
I don't see a server logfile generated anywhere, but the console itself effectively reaches this point:
![Untitled-1](https://github.com/fuzziqersoftware/newserv/assets/13863112/a80fee0b-a561-4ab7-9c4b-eb18ed489810)
Full Console Output: https://pastebin.com/xiRa5te2

..and never progresses beyond it. Even when on the frozen patch screen, nothing ever shows up here. The server is running, and if shutdown the game will error out with a disconnect message but.. Yeah, otherwise it's as though the client is waiting for something to happen that never does.

It seems very likely I think that this happened when the patch server was moved to its own thread yeah, as I've been looking through the commits and I notice that was the very next change after the last working build.

**Comment by fuzziqersoftware** [comment] 2024-03-26 05:43
It appears we can't trust Cygwin and libevent to do the right thing when multiple threads are involved. The Cygwin build of libevent doesn't have event_use_windows_threads (even though it probably should!), so we use event_use_pthreads on all platforms. It seems that this doesn't correctly set up an event_base for multithreaded usage on Windows, so events on the patch server threads never trigger. The Windows build environment is kind of a mess (a story for another time) and making newserv build without Cygwin would be a huge time sink and destroy the codebase, so I've instead moved the patch server back to the main thread on the Windows build. The newest release has this change and should work properly; please test it and post your results here.

**Comment by RaikohKatsushiro** [comment] 2024-03-26 09:53
@nolrinale I think you misunderstood me. I didn't download or use the JP client, I kept testing with EN Tethealla, thus my surprise on having it switch to JP after patching. I "solved it" by doing another clean install of the client and this time leaving patch-bb empty (something there was the culprit, just not sure what yet).

@fuzziqersoftware Using the latest release (2024-03-25), it now goes past patch screen!
I still get the same error I described in OP when starting server, if I fill the patch-bb folder with only the client's data. But if I just leave it empty, or include unitxt_e.prs from the server in there, it will run successfully. Still using EN Tethealla client, for clarity.

**Comment by nolrinale** [comment] 2024-03-26 10:45
Well the fix was already uploaded for Windows, so now it has to be something regarding the client files you are using, but as the bare minimum the server requires you to place all client map and GSL files into the patch server so the game can load properly all the map data, objects and monsters.

You can also copy all the map files found in the `newserv/system/maps/bb-v4` folder and place them into the patch server folder, these are the default ones newserv uses

Give it a try see if it finally lets go you in-game

**Comment by KrisanThyme** [comment] 2024-03-26 17:13
[RaikohKatsushiro](https://github.com/RaikohKatsushiro) I'd recommend doing the following:
Go [https://github.com/fuzziqersoftware/newserv/tree/master/notes/psobb](here) and copy the files from "[jpbb-resources](https://github.com/fuzziqersoftware/newserv/tree/master/notes/psobb/jpbb-resources)" folder into your Teth clients data folder, then do the same thing with [usbb-resources](https://github.com/fuzziqersoftware/newserv/tree/master/notes/psobb/usbb-resources). After that follow the instructions in[english-client-setup.txt](https://github.com/fuzziqersoftware/newserv/blob/master/notes/psobb/english-client-setup.txt) to patch your Teth executable.. Now copy all your Map dats, data.gsl, unitxt_e.prs, and unitxt_j.prs to your "NewServ\system\patch-bb\data" directory. Restart the server and try accessing the patch screen and all should be well (and in english besides).

**Comment by RaikohKatsushiro** [comment] 2024-03-26 19:11
As mentioned in my previous post, I had already managed to connect and go in-game after taking the actions I listed there. Although I didn't play enough to make sure there wouldn't be some crashes or server-client discrepancies. So I'll be sure to look into those extra steps, thanks! I'm guessing they can also be applied to the EN Tethealla client I've been using. Anyways, allow me some time to play and experiment to see if all's good now, or alternatively feel free to close this issue and I can open a new one later if need be.

I would however suggest adding these steps to the README.md as [the current steps there](https://github.com/fuzziqersoftware/newserv?tab=readme-ov-file#client-patch-directories) don't seem enough to get things working on the recommended clean EN Tethealla client and a clean server, and would prevent further confusion from newbies like me :)

**Comment by RaikohKatsushiro** [comment] 2024-03-26 19:59
Quick question: compared to the previous working Windows build (2024-02-10), I noticed this latest one doesn't seem to support some server commands such as set-event. Is this a deliberate change?

When I attempt to instead run the $event command in a lobby, I get a message saying I don't have permission for that command. How do I elevate an account's permissions? None of the files in `system/players/` seem to be human-readable. Feel free to just point me to any documentation I may have missed or even the code that implements such server commands. Thanks.

**Comment by Matt-Swift** [comment] 2024-03-26 20:02
Type `help` in the shell for a list of things that you can do (there are many).

You would need to `update-license SERIAL-NUMBER flags=root` (as an example) to give a player account full permissions on the server. There are a lot of options, `help` will explain them to you.

**Comment by RaikohKatsushiro** [comment] 2024-03-26 20:18
I did check `help` but missed it. Updated license, relogged, it works. Thanks!

On one last related sidenote, is there a way to silence server logs or somehow control which ones are being shown? On a "busy" server it'd be difficult to read the output for commands like `help`.

**Comment by Matt-Swift** [comment] 2024-03-26 20:19
Check the `LogLevels` section in `config.json`.

**Comment by fuzziqersoftware** [comment] 2024-03-30 04:38
I've updated the readme to be a bit more clear about these things. It sounds like this is resolved for everyone, so I'm closing this now. If you run into this again, please reopen this ticket.

**Closed by fuzziqersoftware** 2024-03-30 04:38 UTC

**Comment by RaikohKatsushiro** [comment] 2024-03-30 23:28
I have been fooling around with PSO BB on newserv a bit for the last couple days, and this does seem to be resolved.

Thank you all for the help, and thank you very much fuzziqersoftware for doing this project and making it public and open source! This is amazing, and I hope to be able to properly understand and tweak around with this myself someday :)
