### ISSUE TITLE
[Blue Burst] Gal Gryphon incorrectly initialized 

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#205] opened 2023-11-18 22:14 UTC
Starting a Normal Episode 2 room free exploration we port to Gal Gryphon with $warp and upon defeating him (and making sure you have $debug on) you will notice the game thinks Gal Gryphon is Olga_FLown??? wont drop anything.

Log
[EP2GalGryphonInitError.txt](https://github.com/fuzziqersoftware/newserv/files/13401589/EP2GalGryphonInitError.txt)

**Comment by fuzziqersoftware** [comment] 2023-11-19 06:50
I couldn't reproduce this... which client are you using? Also, have you put your client's data files in system/patch-bb/data? If not, the server would use the default map files, which may be wrong for your client.

**Comment by nolrinale** [comment] 2023-11-19 17:52
All the tests I do over here are always with just the default Tethealla12513 client, in the data folder all i placed was the client's maps files and it's data.gsl as the readme mentions

**Comment by fuzziqersoftware** [comment] 2023-11-20 07:09
This should be fixed by d1866c9b. When creating the Sinow Zoa enemies in Seabed, the server created an incorrect number of clones, which caused all the enemies after the Zoas (including bosses) to have incorrect enemy IDs on the server side.

**Closed by fuzziqersoftware** 2023-11-20 07:09 UTC
