### ISSUE TITLE
[Episode 3] AP Assist has no effect

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#110] opened 2023-09-08 22:09 UTC
The ability "AP Assist" from card 0117 "Hyze" does not appear to have any effect online - tested next to a couple of creature cards (Hildebear and Pan Arms) and both did 6 and 1 respectively.

Let me know if you need any further information.

**Comment by fuzziqersoftware** [comment] 2023-09-09 06:55
This is fixed now. It was probably caused by the same bug as #109.

**Closed by fuzziqersoftware** 2023-09-09 06:55 UTC
