### ISSUE TITLE
[Ep3 NTE] Disconnect when CPU used Dodge

### ISSUE THREAD

**Issue by ShiftaDeband** [fuzziqersoftware/newserv#387] opened 2024-02-12 05:21 UTC
**Describe the bug**
While in a match, a CPU used a defense card and we all disconnected. The last line was a segmentation fault.

**To reproduce**
Not sure there's a 100% replication here. This was during a scenario (Scenario 1, I believe) with the following setup:
Team A: Client 1, CPU
Team B: Client 2, CPU

Made it far into the match, was attacking CPU on Team B when the CPU used Dodge, a +2 Defense card. 

![DPSJ8P_2024-02-11_21-59-46](https://github.com/fuzziqersoftware/newserv/assets/40249870/d60f388d-d60f-4270-b033-1c1dd05fde77)

**Game version(s) (choose one or more of the following):**
GC Ep3 NTE

**Server log output**
[Untitled 2.txt](https://github.com/fuzziqersoftware/newserv/files/14235308/Untitled.2.txt)

**Additional context**
I don't believe I have much to be able to provide. I will try to capture future matches in video and output to a logfile to assist with debugging just to be safe. **Should I be using a more verbose log output?**

In the capture above, and before the match, I was testing an issue with Word Select that existed on the NTE where, while using the first version of the NTE English Action Replay code, if you used some word selects, the other clients would crash. It wasn't an intentional thing when the code was made, but I wanted to test if that was the case here. I believe that since you have protections around word select that it shouldn't be an issue.

**Comment by fuzziqersoftware** [comment] 2024-02-12 05:42
This has been fixed by 46e509aa. The cause was a copy/paste error I made in the function that replaces targets; if you do multiple attacks on a Hunters-side SC, and all of their items are destroyed before the last attack lands, the code that redirects later attacks to land on the SC card was broken.

It turns out having the full log (exactly what you posted) is very helpful; I can modify it slightly and then replay it as if it were a functional test to quickly reproduce the issue.

**Closed by fuzziqersoftware** 2024-02-12 05:42 UTC
