### ISSUE TITLE
[Dreamcast V1] Item ID out of range

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#392] opened 2024-02-18 10:04 UTC
**Describe the bug**
If a drop in the rare drop table has an invalid item ID for the version being played, the player will disconnect when attempting to drop it as an invalid item is being rolled. This is an easy fix: Fix the item by resolving the item ID in the drop table or defining the item in the item files.

However the reason I make a ticket for this is that Dragon and De Rol Le actually have authentic typos in their ItemRT file, causing the rare drop table to be:

```
"DE_ROL_LE": [["1/2", 0x030009, "!ID:030009 x0"]],
"DRAGON": [["1/2", 0x030005, "!ID:030005 x0"]],
```

Which are correctly fixed to be Scape Doll and Star Atomizer respectively in V2.

**To reproduce**
1. Defeat Dragon or De Rol Le on DCv1 with vanilla rare table files.

**Game version(s) (choose one or more of the following):**
DCv1

**Server log output**
```
I 2079396 2024-02-18 02:48:53 - [Commands] Received from C-159 (Rudramadum) (version=DC_V1 command=62 flag=00)
0000 | 62 00 18 00 60 05 00 00 0C 2D 1D 06 33 33 5F C2 | b   `    -  33_ 
0010 | F6 28 71 42 01 00 00 00                         |  (qB            
I 2079396 2024-02-18 02:48:53 - [Game:36] Drop check for E-61D DE_ROL_LE
I 2079396 2024-02-18 02:48:53 - [Game:36] Creating item from enemy 061D (area 0C)
I 2079396 2024-02-18 02:48:53 - [ItemCreator:DC_V1/Ep1/Nml/N/0] Enemy type: 2D; random state: E41DB156 00000D07
I 2079396 2024-02-18 02:48:53 - [ItemCreator:DC_V1/Ep1/Nml/N/0] Drop chosen (58 < 100)
W 2079396 2024-02-18 02:48:53 - [Server] Error processing client command: item ID out of range
I 2079396 2024-02-18 02:48:53 - [Server] Client disconnected: C-159 on fd 38
```

**Additional context**
I will probably fix this issue by having the intended items drop on V1, but I didn't want to do this on newserv's table as I figured you might want to be able to handle the authentic V1 tables, even if they are bugged.

**Comment by fuzziqersoftware** [comment] 2024-02-19 07:04
Thanks for finding the root cause. This has been fixed by cda86e58; we now just warn and don't fail when an invalid item is generated.

**Closed by fuzziqersoftware** 2024-02-19 07:04 UTC
