### ISSUE TITLE
Error cannot connect dns server

### ISSUE THREAD

**Issue by ButtonMash64** [fuzziqersoftware/newserv#432] opened 2024-03-10 01:50 UTC
**Describe the bug**
hi I’m setting config file with my ip adress and open newserv.exe and try to connect pso 1&2 with dolphin emulator set emulator config sp1 to network TAP and try to connect online to pso and I have error cannot connect to dns server

**Game version(s) (choose one or more of the following):**
GC Ep1&2, with Dolphin

**Server log output**
Use Windows

**Additional context**
configure network option in game exactly to mention it your page :)

**Comment by Matt-Swift** [comment] 2024-03-10 08:39
Firstly, "TAP" in Dolphin is not the same as tapserver, so this will not work; tapserver is currently implemented in a fork of Dolphin but not the main release.

Secondly, if newserv is on the same computer, connecting to it will unfortunately fail as PSO ignores DNS requests on loopback.

So, here's how to fix this assuming same PC:

1. Set your server address in config.json to 127.0.0.1.
2. Use an AR code for the version of PSO you are using from this page: https://ragol.org/localnewserv (if not sure on the version, just try them all)
3. Use this version of Dolphin with the HLE BBA pointing at 127.0.0.1 or 8.8.8.8 in settings because you will FSOD otherwise: https://dolphin-emu.org/download/dev/master/5.0-16838/

**Comment by ButtonMash64** [comment] 2024-03-10 15:29
I tried what you suggested.  The server is on another pc, but it's connected to the same network. 

I tried what you suggested, but I still get the same error.

in the config file I've entered 127.0.0.1 in local address and my ip address in external address

in the dolphin emulator of the version you asked me to download I don't see the HLE, I have all the options but instead of HLE I see "Broadband adapter (Built In)" I tried anyway with this option but it didn't work. I also tried with another version that I see the HLE. But I got exactly the same error.

I also entered the right version's action replay code, as you asked me to do.

**Comment by Matt-Swift** [comment] 2024-03-10 15:31
In that case, my instructions are not correct as the server is on the same network.

You need to put in your 192.168.x.x address in your local address field, and then set built-in Broadband Adapter to this address in Dolphin as well - remove the AR code.

This should work, although it's possible that PSO will still not connect to a server on the same network, meaning you would need an AR code that points to your IP address of the other computer.

**Comment by ButtonMash64** [comment] 2024-03-11 20:43
I've tried, but unfortunately I still get the same error, although my local ip in the config file is correct, my external ip address is the right one. I've also checked with the whatmyip website. in dolphin I've chosen the HLE adapter and I've tried by entering my local ip, as well as my ip from the whatmyip website...

**Comment by Matt-Swift** [comment] 2024-03-11 21:20
You should be connecting on your local IP (make sure local address in config.json is your local address), and the external address is your external IP address.

Your ports need to be forwarded for this to work properly.

**Comment by ButtonMash64** [comment] 2024-03-11 21:22
oh oki thanks, i guess u need to open port 53 ? or another port ?

**Comment by Matt-Swift** [comment] 2024-03-11 21:26
Check the port configuration in config.json to see exactly what you need to forward, but you will need to forward UDP 53 for the DNS server, and TCP 5100-5124 and 9000-9103 at the very least for GameCube Episode I & II.

I personally just forwarded every port in config.json so I could connect everything to it.

**Comment by ButtonMash64** [comment] 2024-03-11 22:01
ok i tried everything, sometime i succeeded with a test with another ip than my local ip, but after i closed the emulator and reopened it to test with pso3 it was impossible to connect...

a friend of mine told me to try with the ip of the software called Hamachi. i tried, but that didn't work either :(

**Comment by Matt-Swift** [comment] 2024-03-12 18:12
Hamachi is for virtual private LAN networks over the internet, and is not what you need here.

The ports I told you to forward were simply for Episode I & II only since that's all you said you were playing. You will need to also forward 9200-9204 for Episode 3.

**Comment by ButtonMash64** [comment] 2024-03-12 23:01
I've tried everything you've told me, but unfortunately nothing changes, always the same error #102 :(

**Comment by Matt-Swift** [comment] 2024-03-13 18:05
I'm guessing that you've never used server software before, so you're not too familiar with how these things work.

Assuming that, let's step back to the beginning.

1. Download newserv from one of the latest releases (probably not the latest, there is a somewhat critical bug currently)
2. Modify `config.example.json` and put your 192.166.x.x address in `LocalAddress`, and your router address in `ExternalAddress`.
3. Rename `config.example.json` to `config.json`.
4. Unblock/forward *all* ports that are listed in the config.json file; they are all the numbers under `PortConfiguration`.
5. With this done, launch newserv.exe and it should launch correctly.
6. For your set up, edit the DNS address in Dolphin's Built-in BBA to your 192.168.x.x address.
7. For your friends' set up, edit the DNS address in Dolphin's Built-in BBA to your router address.

No set up is required in game if using Dolphin, but if using GameCube/Wii, go to Provider Settings and use a manual DNS server and set that to the appropriate address.

In the event that your friends are able to connect but you are not, this means that PSO is refusing to connect to the server on the same local address, and you will need an AR code or ISO patch to bypass it.

**Comment by ButtonMash64** [comment] 2024-03-15 03:03
hello, yes indeed, I'm new to creating servers. I did what you asked. Concerning port forwarding I entered 9000,9001 (these are the only ones I saw from where you told me to look).

I managed to connect locally with the server on one pc and the game on another pc. But remotely, it never wants to work. I think the problem comes from my modem/router which is having trouble accepting port forwarding...

**Comment by Matt-Swift** [comment] 2024-03-15 08:23
There are much more than 9000 and 9001 - if you only forwarded those ports, it's not going to work remotely because the ports aren't forwarded that you need.

They are here in config.json:

![image](https://github.com/fuzziqersoftware/newserv/assets/33199242/0735b60c-40af-44b1-8e3f-6565dcee5551)
![image](https://github.com/fuzziqersoftware/newserv/assets/33199242/4f7402f7-d566-4e4f-a0a6-7410321ceffd)

**Comment by nolrinale** [comment] 2024-03-31 15:14
@ButtonMash64 if the issue is resolved, please close this ticket

**Comment by fuzziqersoftware** [comment] 2024-04-03 02:12
I'm going to assume the issue has been resolved. If not, feel free to reopen this.

**Closed by fuzziqersoftware** 2024-04-03 02:12 UTC
