### ISSUE TITLE
[Blue Burst] Client crashes on newest version

### ISSUE THREAD

**Issue by toiletman74** [fuzziqersoftware/newserv#255] opened 2023-12-05 05:48 UTC
My client keeps crashing on the loading screen after selecting a character on the newest version of newserv.

**Comment by fuzziqersoftware** [comment] 2023-12-05 05:56
Can you provide more details? Specifically, a screenshot of the crash and the full console output from the server would be useful.

**Comment by fuzziqersoftware** [comment] 2023-12-05 05:57
Also, uploading the contents of your system/players folder would be useful for me to test with.

**Comment by toiletman74** [comment] 2023-12-05 09:21
[console output.txt](https://github.com/fuzziqersoftware/newserv/files/13557629/console.output.txt)
[players.zip](https://github.com/fuzziqersoftware/newserv/files/13557674/players.zip)
this time I got to the point where I was loading into the lobby before it crashed

**Comment by toiletman74** [comment] 2023-12-05 21:22
The last release works fine 🤔 I'll try a fresh install tho and see what happens

**Comment by toiletman74** [comment] 2023-12-05 22:30
I tried a fresh copy of teth ver 12513 and it still crashes at either the loading screen after picking a character or the loading screen to the lobby

**Comment by Matt-Swift** [comment] 2023-12-05 22:31
Did you put all the map files in `patch-bb/data` like the README suggests? Not just your modified ones.

**Comment by toiletman74** [comment] 2023-12-05 22:46
I just tried putting all the map files in patch-bb/data without my system/players and system/licenses and I got this after choosing a character 
![image](https://github.com/fuzziqersoftware/newserv/assets/91436591/64aeb411-5563-4711-b0bb-c4d7f7d83ec8)
I also tried it with my system/players and system/licenses and it crashed during the loading screen after picking a character

**Comment by toiletman74** [comment] 2023-12-05 22:54
Maybe something got messed up while I was building newserv? I'll try rebuilding it.

**Comment by toiletman74** [comment] 2023-12-05 23:05
Tried it with a fresh build, it still crashes in the same spot

**Comment by fuzziqersoftware** [comment] 2023-12-06 18:05
I also could not reproduce this; I used the players files you posted above and I was able to choose a character, join the lobby, create a game, and go to Forest 1 with no problems. It seems likely to me that either a client modification or client setting is at fault here; does it still crash if you use a clean install and default graphics/sound/etc. settings?

**Comment by MADrewry** [comment] 2023-12-06 19:04
Don't know if it's appropriate for me to speak here but I thought would put in my two cents anyway. I tried this last night and also could not reproduce the error. Got all the way to forest 1 with no problem.

**Comment by toiletman74** [comment] 2023-12-10 22:49
I'm still getting problems with crashing. would you be able to post a new build on the releases page? Maybe there's a problem with how I'm building newserv.

**Comment by fuzziqersoftware** [comment] 2023-12-11 06:57
I've built a new release and uploaded it just now.

**Comment by toiletman74** [comment] 2023-12-11 23:24
the release doesn't crash. it must've been a problem with the way I was building it :o

**Comment by nolrinale** [comment] 2023-12-24 10:26
Lets close this ticket

**Comment by fuzziqersoftware** [comment] 2023-12-25 06:52
An undefined behavior bug has been fixed recently, which is possibly related to the issue you've seen. I've also uploaded a more recent release a day or two ago.

If anyone else comes across this issue in the future, please do the following:
- Make sure you're using a clean/unmodified client (original US or JP, or Tethealla "TethVer12513" are known to work properly)
- Try to reproduce the crash with a minimal set of changes from newserv's release state (that is, try to get the crash to happen with the smallest possible number of changes to config.json and other files in system/)
- If you can get the crash to happen reliably, post the full log taken with `"HideDownloadCommands": false` in config.json

**Closed by fuzziqersoftware** 2023-12-25 06:52 UTC
