### ISSUE TITLE
[Blue Burst] Some EP4 enemies drops too much meseta

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#198] opened 2023-11-15 11:16 UTC
A rare bug where the Yowie drops more than 1000 meseta, this happens with or without quest loaded. In this case I tested by loading the quest MAIXMUM ATTACK 3 v2 but it also happens in free exploration mode. 

This only affects the Yowie not the Satellite Lizard but i notice weird messages in the log about all Episode 4 enemies in this area regardless.

Likewise this problem is also affecting the Goran, but it doesnt affect the Pyro Goran or the Goran Detonator

Affects also MELISSA_A and GIRTABUBLU

Log
[Meseta1KYowieVHEP4.txt](https://github.com/fuzziqersoftware/newserv/files/13363897/Meseta1KYowieVHEP4.txt)
[Meseta1KGolanVHEP4.txt](https://github.com/fuzziqersoftware/newserv/files/13364175/Meseta1KGolanVHEP4.txt)
[Meseta1KGirtabubluVHEP4.txt](https://github.com/fuzziqersoftware/newserv/files/13364384/Meseta1KGirtabubluVHEP4.txt)

**Comment by fuzziqersoftware** [comment] 2023-12-06 17:57
This was caused by the ItemPT data being simply wrong. I've reformatted and recreated the Episode 4 data, and this should be fixed now.

**Closed by fuzziqersoftware** 2023-12-06 17:57 UTC
