### ISSUE TITLE
[Blue Burst] Overdrafting Meseta diconnects client (default behaviour?) Can it be changed?

### ISSUE THREAD

**Issue by MADrewry** [fuzziqersoftware/newserv#172] opened 2023-11-05 05:05 UTC
I ran into an issue in the item shop when purchasing a stack of items. Somehow I overdrafted my Mesata which immediately disconnected the client. I am not sure how this occurred as I thought you could not purchase more items than you had Meseta to purchase.
I see from the config.json that disconnecting the client for overdrafting is default behavior if  "Episode3InfiniteMeseta" is set to false, does this setting also apply to Blue Burst? Unfortunately I was not capturing logs at the time this occurred and only saved the last few lines when the event occurred. I have also not been able to reproduce the event so this may be moot.
However in any case if the default behavior is to disconnect the client, is it possible to change that to something less severe? This happened to me mid-quest while I was resupplying and caused the quest to be reset. Not sure if useful but what little bit of the log I captured is below:

I 2922 2023-11-04 19:19:01 - [Commands] Received from C-38 (    ECherry2000) (version=BB command=0062 flag=00000000)
0000 | 14 00 62 00 00 00 00 00 B7 03 FF FF 0E 00 01 00 |   b
0010 | 00 01 06 00                                     |
W 2922 2023-11-04 19:19:01 - [Server] Error processing client command: player does not have enough meseta
I 2922 2023-11-04 19:19:01 - [Server] Client disconnected: C-38 on fd 35

**Comment by fuzziqersoftware** [comment] 2023-11-05 05:17
The config.json setting applies only to Episode 3 Meseta. On BB, overdrafting Meseta is never allowed because an overdraft means that the client's and server's view of the game went out of sync.

There is a known bug where selling items at shops sometimes gives incorrect amounts of Meseta on the server side, which I think is likely the cause of the issue you saw. (Probably you sold something before this, the server gave you less Meseta than the client gave you for that sale, and when you then attempted to buy something, the client allowed the purchase but the server did not.) If the issue occurs again, it would be helpful if you could upload a full game log (all server output from the time the game started through the time the disconnect occurred). By replaying the commands from the log to step through the event sequence, we would be able to find out exactly where the client and server went out of sync.

**Comment by MADrewry** [comment] 2023-11-05 06:15
Thanks for that info, that does indeed sound like my situation, as I was selling collected items before purchasing. I will indeed log the output moving forward in case this or other issues crop up. On the subject of logging, is there an in game command for sending output to a log file or do I just need to use something like the script command (I'm running on Linux) and send all output to a file?

**Comment by fuzziqersoftware** [comment] 2023-11-06 01:27
There's currently no in-game command for logging, though this would be a useful feature for me to add in the future. For now, the best way to capture log output is to redirect (or tee) stderr to a log file.

**Comment by MADrewry** [comment] 2023-11-06 01:46
Now that I understand the cause of the issue it didn't take long to recreate the disconnect issue. Attached is the game log of today's session where I was able to duplicate the disconnect. Recorded with script, hopefully it didn't mangle the formatting. This is from patch server connect to disconnect. Let me know if you need more or in another format.
[psobbgamelog.zip](https://github.com/fuzziqersoftware/newserv/files/13261722/psobbgamelog.zip)

**Comment by MADrewry** [comment] 2023-11-06 02:22
Sorry, I didn't see your last comment until after uploading my last log. However it looks like currently I can recreate the disconnect on demand by simply attempting to purchase a disk:barta lv2, without having even sold anything beforehand. attached is a new log output using tee so the formatting looks cleaner. (forgot to trim the log so this is from server launch to disconnect,)
[log.zip](https://github.com/fuzziqersoftware/newserv/files/13261845/log.zip)

**Comment by fuzziqersoftware** [comment] 2023-11-06 02:44
Thanks for the detailed report, and the logs. It looks like there was a bug specifically with technique disks - the server used an incorrect part of the item data to calculate the price, so it ended up using a much higher price than the client for most tech disks. This is fixed by commit 1deb5e0.

I also spot-checked several other items, including a few rare weapons, some common weapons with specials and bonuses, some common shields, armors, and units, and a few other tool items. Everything else I checked had the correct price, so hopefully this was the only bug in the price computation. Feel free to open another issue here if you experience more problems after this fix.

**Closed by fuzziqersoftware** 2023-11-06 02:44 UTC
